**Step 1 - Generate a 10x10 random matrix**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import numpy as np
np.random.seed(42)# To stop the random matrix from keep changing
matrix = np.random.randint(0, 2, (10, 10))# To generate matrix in form of 0 and 1
print("Initial matrix:\n", matrix)

Initial matrix:
 [[0 1 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 0 1 0 0 0]
 [0 0 1 1 1 1 1 0 1 1]
 [0 1 0 1 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 1 1]
 [1 1 0 1 0 1 1 1 0 1]
 [0 1 0 1 0 0 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 0]]


**Step 2 - Print row with lowest fitness value and Corresponding fitness function**

In [4]:
fitnesses  = np.sum(matrix, axis=1)# Count ones for each row
print("Number of ones in each row:", fitnesses )
lowest_ones_index = np.argmin(fitnesses )# Identify the row with the lowest number of ones
lowest_ones_row = matrix[lowest_ones_index].tolist()
print("Row with the lowest number of ones:", lowest_ones_row)
print("Fitness function:", fitnesses [lowest_ones_index])

Number of ones in each row: [3 4 9 4 7 4 4 7 5 9]
Row with the lowest number of ones: [0, 1, 0, 0, 0, 1, 0, 0, 0, 1]
Fitness function: 3


**Step 3 - Apply the roulette wheel Selection Algorithm**

Algorithm:-

1.   Calculate S = the sum of a finesses.
2.   Generate a random number between 0 and S.
3.   Starting from the top of the population, keep adding the finesses to the
     partial sum P, till P<S. ( Calculate cumulative sum)
4.   The individual for which P exceeds S is the chosen individual.

Example:-
1. 11010 (Fitness = 3)

  01100 (Fitness = 2)

  11110 (Fitness = 4)

  10101 (Fitness = 3)

  10000 (Fitness = 1)

  Calculate S = the sum of the fitnesses. (S=3+2+4+3+1=13)
2.Generate a random number between 0 and S. (Let's say our randomly generated number, r, is 7.4.)
3.Starting from the top of the population, keep adding the fitnesses to the partial sum P, till P<r.
Start with the first individual:

  P=3 (after adding fitness of 11010)

  Move to the second individual:

  P=5 (after adding fitness of 01100)

  Move to the third individual:

  P=9 (after adding fitness of 11110)

  Now, P has exceeded our random number, r.
4.The individual for which P exceeds r is the chosen individual.
Based on our running total, the third individual (11110 with fitness 4) makes the partial sum exceed our random number, so it's the selected individual.
 (For our random number 7.4, the selected individual from the given dataset would be 11110.)
5.Now repeat the same process for 10 times to get a 10 x 10 updated matrix


In [5]:
S = sum(fitnesses)                                                        # Calculate sum of fitnesses from each row
selected_indices = []                                                     # Initialize empty list to keep the rows selected in Roulette wheel Selection method
for _ in range(10):                                                       # Repeat 10 times to fill our new matrix
    r = np.random.uniform(0, S)                                           # This line generates a random float number between 0 and S (our total fitness)
    P = 0                                                                 # We initialize a variable P to 0.I(To keep track of the cumulative sum of fitnesses as iterating over rows.)
    for idx, f in enumerate(fitnesses):                                   # Iterate over our rows using a for-loop, getting the index (idx) and fitness value (f) of each individual.
        P += f                                                            # For every individual, we add its fitness to P.
        if P > r:                                                         # If P has exceeded our random number r. If it has, it means we have found our selected individual
            selected_indices.append(idx)                                  # We then add its index to the selected_indices list
            break

transformed_matrix = matrix[selected_indices]
print("\nTransformed matrix using Roulette Wheel Selection:")
print(transformed_matrix)



Transformed matrix using Roulette Wheel Selection:
[[1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 0 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1]
 [0 1 0 0 0 1 0 0 0 1]
 [0 0 1 1 1 0 1 0 0 0]]


**Step 4 - Applying Crossover betweeen two consecutive rows**

Algorithm:-
1. Select the crossover point
2. Flip the values after C.P. to other sides

Example:-

Given the two genes 10110 and 11011 and a crossover point of 3

Gene 1: 101 | 10

Gene 2: 110 | 11

After crossover:

New Gene 1: 101 | 11 -> 10111

New Gene 2: 110 | 10 -> 11010

Code:-

Row i:     10110

Row i+1:   11011

After crossover point at 3

New Row i:     11010

New Row i+1:   10111




In [6]:
for i in range(0, 10, 2):                                                              # Iterate over every second row of the transformed_matrix (i.e., rows with indices 0, 2, 4, 6, and 8).
                                                                                       # Each pair of consecutive rows (like rows 0 & 1, rows 2 & 3, etc.) will be involved in the crossover
    crossover_point = np.random.randint(1, 9)                                          # A random C.P. between indices 1 (inclusive) and 9 (exclusive) is generated.
    temp = np.copy(transformed_matrix[i, :crossover_point])                            # makes a copy of the portion of the row i up to the C.P. and stores in the temp variable.
    transformed_matrix[i, :crossover_point] = transformed_matrix[i+1, :crossover_point]# portion of row i up to the C.P. is replaced with the corresponding portion of the next row (i+1).
    transformed_matrix[i+1, :crossover_point] = temp                                   #The portion of row i+1 up to the C.P. is replaced with the originally copied portion of row i (stored in temp).

print("\nMatrix after Crossover:")
print(transformed_matrix)


Matrix after Crossover:
[[0 1 0 1 0 0 1 0 1 0]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 0 0 0 1 1 0 1 1]
 [0 0 1 1 1 1 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 0]
 [0 0 0 0 1 0 1 1 1 1]
 [0 0 1 1 1 1 0 0 0 1]
 [0 1 0 0 0 0 1 0 0 0]]


**Step 5 - Mutation of elements**]

Algorithm:-
1. Initialize mutation rate
2. we're visiting each element of the matrix and generating a random number between 0 and 1. If this number is less than M.R. the element (or gene) undergoes mutation.

Example:-
1. Initialize mutation rate= 0.05
2. For element (1,1) = 0:

  Random number generated = 0.07

  Since 0.07 is not less than 0.05, no mutation happens.

  For element (1,2) = 1:

  Random number generated = 0.03

  Since 0.03 is less than 0.05, we mutate. The value changes from 1 to 0.

  ... And so on for each element of the matrix.


In [7]:
mutation_rate = 0.05                                                # 5% mutation rate( Probblity of gene to go under mutation )
for i in range(10):                                                 # Nested loops to iterate over each element of the transformed_matrix, which is assumed to be of size 10x10
    for j in range(10):                                             # For each gene in the matrix, a random number between 0 and 1 is generated
        if np.random.rand() < mutation_rate:                        # if this random number is less than the M.R., the condition becomes true, then element should undergo mutation.
            transformed_matrix[i, j] = 1 - transformed_matrix[i, j] # If the value of the gene is 0, it becomes 1 - 0 = 1. and if  1, then becomes 1 - 1 = 0.

print("\nMatrix after Mutation:")
print(transformed_matrix)


Matrix after Mutation:
[[0 1 0 1 0 0 0 0 1 0]
 [0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 0 1 1 1 1 1 0]
 [1 1 0 0 0 1 1 0 1 1]
 [0 0 1 1 1 1 1 1 1 0]
 [1 0 1 0 1 1 1 1 1 0]
 [0 0 0 0 1 0 1 1 1 1]
 [0 0 1 1 1 1 1 0 0 1]
 [0 1 0 0 0 0 1 0 0 0]]


**For 50 iterations**

In [8]:
import numpy as np

np.random.seed(42)

def genetic_algorithm(matrix):
    fitnesses = np.sum(matrix, axis=1)
    S = sum(fitnesses)
    selected_indices = []

    for _ in range(10):
        r = np.random.uniform(0, S)
        P = 0
        for idx, f in enumerate(fitnesses):
            P += f
            if P > r:
                selected_indices.append(idx)
                break

    transformed_matrix = matrix[selected_indices]

    for i in range(0, 10, 2):
        crossover_point = np.random.randint(1, 9)
        temp = np.copy(transformed_matrix[i, :crossover_point])
        transformed_matrix[i, :crossover_point] = transformed_matrix[i+1, :crossover_point]
        transformed_matrix[i+1, :crossover_point] = temp

    mutation_rate = 0.05
    for i in range(10):
        for j in range(10):
            if np.random.rand() < mutation_rate:
                transformed_matrix[i, j] = 1 - transformed_matrix[i, j]

    return transformed_matrix

matrix = np.random.randint(0, 2, (10, 10))
for iteration in range(50):
    Matrix = genetic_algorithm(matrix)

fitnesses_B = np.sum(matrix, axis=1)
fitnesses_A = np.sum(Matrix, axis=1)
lowest_ones_index_A = np.argmin(fitnesses_B)
lowest_ones_index_B = np.argmin(fitnesses_A)
lowest_ones_row_A = Matrix[lowest_ones_index].tolist()
lowest_ones_row_B = matrix[lowest_ones_index].tolist()
print("Initial matrix before 50 iterations:\n", matrix)
print("Final matrix after 50 iterations:\n", Matrix)
print("Row with the lowest number of ones before 50 iterations:", lowest_ones_row_A)
print("Row with the lowest number of ones after 50 iterations:", lowest_ones_row_B)
print("Fitness function before 50 iteration:", fitnesses[lowest_ones_index_B])
print("Fitness function after 50 iteration:", fitnesses[lowest_ones_index_A])

Initial matrix before 50 iterations:
 [[0 1 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 0 1 0 0 0]
 [0 0 1 1 1 1 1 0 1 1]
 [0 1 0 1 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 1 1]
 [1 1 0 1 0 1 1 1 0 1]
 [0 1 0 1 0 0 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 0]]
Final matrix after 50 iterations:
 [[0 0 0 0 0 0 1 0 1 1]
 [0 1 0 1 0 0 1 0 1 1]
 [1 1 0 1 0 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 0]
 [1 0 1 0 1 0 1 1 1 1]
 [0 0 0 1 1 1 1 1 1 1]
 [0 0 1 0 0 1 1 0 1 1]
 [0 1 1 1 1 0 1 0 0 0]
 [0 0 0 0 1 0 1 0 0 1]
 [0 1 0 0 0 1 0 1 1 0]]
Row with the lowest number of ones before 50 iterations: [0, 0, 0, 0, 0, 0, 1, 0, 1, 1]
Row with the lowest number of ones after 50 iterations: [0, 1, 0, 0, 0, 1, 0, 0, 0, 1]
Fitness function before 50 iteration: 3
Fitness function after 50 iteration: 3


**Loading Colon Cancer Dataset**

In [9]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dsa assignment /State scholarship documents /cervical_cancer_csv.csv')
df

Unnamed: 0  Age  Number of sexual partners  First sexual intercourse  \
0             0   18                        4.0                   15.0000   
1             1   15                        1.0                   14.0000   
2             2   34                        1.0                   16.9953   
3             3   52                        5.0                   16.0000   
4             4   46                        3.0                   21.0000   
..          ...  ...                        ...                       ...   
853         853   34                        3.0                   18.0000   
854         854   32                        2.0                   19.0000   
855         855   25                        2.0                   17.0000   
856         856   33                        2.0                   24.0000   
857         857   29                        2.0                   20.0000   

     Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
0                   1.0     0.0             0.0                  0.0   
1                   1.0     0.0             0.0                  0.0   
2                   1.0     0.0             0.0                  0.0   
3                   4.0     1.0            37.0                 37.0   
4                   4.0     0.0             0.0                  0.0   
..                  ...     ...             ...                  ...   
853                 0.0     0.0             0.0                  0.0   
854                 1.0     0.0             0.0                  0.0   
855                 0.0     0.0             0.0                  0.0   
856                 2.0     0.0             0.0                  0.0   
857                 1.0     0.0             0.0                  0.0   

     Hormonal Contraceptives  Hormonal Contraceptives (years)  ...  \
0                        0.0                              0.0  ...   
1                        0.0                              0.0  ...   
2                        0.0                              0.0  ...   
3                        1.0                              1.0  ...   
4                        1.0                              1.0  ...   
..                       ...                              ...  ...   
853                      0.0                              0.0  ...   
854                      1.0                              1.0  ...   
855                      1.0                              1.0  ...   
856                      1.0                              1.0  ...   
857                      1.0                              1.0  ...   

     STDs: Time since first diagnosis  STDs: Time since last diagnosis  \
0                            6.140845                         5.816901   
1                            6.140845                         5.816901   
2                            6.140845                         5.816901   
3                            6.140845                         5.816901   
4                            6.140845                         5.816901   
..                                ...                              ...   
853                          6.140845                         5.816901   
854                          6.140845                         5.816901   
855                          6.140845                         5.816901   
856                          6.140845                         5.816901   
857                          6.140845                         5.816901   

     Dx:Cancer  Dx:CIN  Dx:HPV  Dx  Hinselmann  Schiller  Citology  Biopsy  
0            0       0       0   0           0         0         0       0  
1            0       0       0   0           0         0         0       0  
2            0       0       0   0           0         0         0       0  
3            1       0       1   0           0         0         0       0  
4            0       0       0   0           0         0         0       0  
..         ...     ... 

In [10]:
df.drop('Unnamed: 0',axis=1)

Age  Number of sexual partners  First sexual intercourse  \
0     18                        4.0                   15.0000   
1     15                        1.0                   14.0000   
2     34                        1.0                   16.9953   
3     52                        5.0                   16.0000   
4     46                        3.0                   21.0000   
..   ...                        ...                       ...   
853   34                        3.0                   18.0000   
854   32                        2.0                   19.0000   
855   25                        2.0                   17.0000   
856   33                        2.0                   24.0000   
857   29                        2.0                   20.0000   

     Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
0                   1.0     0.0             0.0                  0.0   
1                   1.0     0.0             0.0                  0.0   
2                   1.0     0.0             0.0                  0.0   
3                   4.0     1.0            37.0                 37.0   
4                   4.0     0.0             0.0                  0.0   
..                  ...     ...             ...                  ...   
853                 0.0     0.0             0.0                  0.0   
854                 1.0     0.0             0.0                  0.0   
855                 0.0     0.0             0.0                  0.0   
856                 2.0     0.0             0.0                  0.0   
857                 1.0     0.0             0.0                  0.0   

     Hormonal Contraceptives  Hormonal Contraceptives (years)  IUD  ...  \
0                        0.0                              0.0  0.0  ...   
1                        0.0                              0.0  0.0  ...   
2                        0.0                              0.0  0.0  ...   
3                        1.0                              1.0  0.0  ...   
4                        1.0                              1.0  0.0  ...   
..                       ...                              ...  ...  ...   
853                      0.0                              0.0  0.0  ...   
854                      1.0                              1.0  0.0  ...   
855                      1.0                              1.0  0.0  ...   
856                      1.0                              1.0  0.0  ...   
857                      1.0                              1.0  0.0  ...   

     STDs: Time since first diagnosis  STDs: Time since last diagnosis  \
0                            6.140845                         5.816901   
1                            6.140845                         5.816901   
2                            6.140845                         5.816901   
3                            6.140845                         5.816901   
4                            6.140845                         5.816901   
..                                ...                              ...   
853                          6.140845                         5.816901   
854                          6.140845                         5.816901   
855                          6.140845                         5.816901   
856                          6.140845                         5.816901   
857                          6.140845                         5.816901   

     Dx:Cancer  Dx:CIN  Dx:HPV  Dx  Hinselmann  Schiller  Citology  Biopsy  
0            0       0       0   0           0         0         0       0  
1            0       0       0   0           0         0         0       0  
2            0       0       0   0           0         0         0       0  
3            1       0       1   0           0         0         0       0  
4            0       0       0   0           0         0         0       0  
..         ...     ...     ...  ..         ...       ...       ...     ...  
853          0       0       0

In [11]:
df.shape

(858, 37)

In [12]:
print(df.iloc[:, 36])

0      0
1      0
2      0
3      0
4      0
      ..
853    0
854    0
855    0
856    0
857    0
Name: Biopsy, Length: 858, dtype: int64


**For dataset of order 50x36 for 100 iterations and then testing on 800x36 for 500 iterations on randomly generated binary dataset**

In [13]:
import numpy as np

np.random.seed(42)

def genetic_algorithm(matrix):
    fitnesses = np.sum(matrix, axis=1)
    S = sum(fitnesses)
    selected_indices = []

    for _ in range(matrix.shape[0]):
        r = np.random.uniform(0, S)
        P = 0
        for idx, f in enumerate(fitnesses):
            P += f
            if P > r:
                selected_indices.append(idx)
                break

    transformed_matrix = matrix[selected_indices]

    for i in range(0, matrix.shape[0], 2):
        crossover_point = np.random.randint(1, matrix.shape[1] - 1)
        temp = np.copy(transformed_matrix[i, :crossover_point])
        transformed_matrix[i, :crossover_point] = transformed_matrix[i+1, :crossover_point]
        transformed_matrix[i+1, :crossover_point] = temp

    mutation_rate = 0.05
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if np.random.rand() < mutation_rate:
                transformed_matrix[i, j] = 1 - transformed_matrix[i, j]

    return transformed_matrix

matrix = np.random.randint(0, 2, (50, 36))
for iteration in range(100):
    matrix = genetic_algorithm(matrix)

fitnesses = np.sum(matrix, axis=1)
lowest_ones_index = np.argmin(fitnesses)
lowest_ones_row = matrix[lowest_ones_index]

positions_of_ones = np.where(lowest_ones_row == 1)[0].tolist()  # Get positions of ones in the row

print("Row with the lowest number of ones:", lowest_ones_row.tolist())
print("Fitness function:", fitnesses[lowest_ones_index])
print("Positions of elements holding ones:", positions_of_ones)

Row with the lowest number of ones: [0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1]
Fitness function: 17
Positions of elements holding ones: [1, 2, 4, 5, 9, 12, 13, 14, 15, 18, 19, 22, 25, 27, 31, 33, 35]


**position counting on the dataset was from 1 rather than 0 so i added plus 1 to each item**

In [14]:
def add_one(list1):
  new_list = []
  for element in list1:
    new_list.append(element + 1)
  return new_list

list1 = [1, 2, 4, 5, 9, 12, 13, 14, 15, 18, 19, 22, 25, 27, 31, 33, 35]
list2 = add_one(list1)

In [15]:
list2

[2, 3, 5, 6, 10, 13, 14, 15, 16, 19, 20, 23, 26, 28, 32, 34, 36]

In [16]:
column_names = df.columns[[2, 3, 5, 6, 10, 13, 14, 15, 16, 19, 20, 23, 26, 28, 32, 34, 36]]

In [17]:
column_names

Index(['Number of sexual partners', 'First sexual intercourse', 'Smokes',
       'Smokes (years)', 'IUD', 'STDs (number)', 'STDs:condylomatosis',
       'STDs:cervical condylomatosis', 'STDs:vaginal condylomatosis',
       'STDs:pelvic inflammatory disease', 'STDs:genital herpes', 'STDs:HIV',
       'STDs: Number of diagnosis', 'STDs: Time since last diagnosis', 'Dx',
       'Schiller', 'Biopsy'],
      dtype='object')

In [18]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

np.random.seed(42)

# Generate a random binary matrix of size 10x10
matrix = np.random.randint(0, 2, (10, 10))

# Let's assume a synthetic data 'X' and target 'y' (this should be your actual dataset)
X = np.random.randn(50, 10)
y = np.random.randint(0, 2, 50)

def calculate_fitness(matrix_row, X, y):
    # Objective 1: Minimize the number of selected features
    objective_1 = sum(matrix_row)

    # Objective 2: Maximize classification accuracy using KNN
    selected_features = np.where(matrix_row == 1)[0]
    if len(selected_features) == 0:  # if no features are selected
        return objective_1, 0
    X_selected = X[:, selected_features]
    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)
    clf = KNeighborsClassifier()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    objective_2 = accuracy_score(y_test, y_pred)

    return objective_1, objective_2

# Storing both objectives for each solution
objective_values = np.zeros((10, 2))
for i in range(10):
    objective_values[i] = calculate_fitness(matrix[i], X, y)

# Pareto dominance to get non-dominated solutions
dominated = []
for i in range(10):
    for j in range(10):
        if i != j and objective_values[i][0] >= objective_values[j][0] and objective_values[i][1] <= objective_values[j][1]:
            dominated.append(i)
            break

non_dominated_solutions = np.delete(matrix, dominated, axis=0)

print("Non-dominated solutions:\n", non_dominated_solutions)


Non-dominated solutions:
 [[0 1 0 0 0 1 0 0 0 1]]


In [19]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

np.random.seed(42)

# Create a placeholder for colon cancer dataset (replace it with your data)
x_colon = df.drop(columns=['Biopsy'])
y_colon = df['Biopsy']

objectives = []

def calculate_fitness(matrix_row, X, y):
    # Objective 1: Minimize the number of selected features
    objective_1 = sum(matrix_row)

    # Filter the columns in the dataset based on the selected features
    selected_features = [i for i, val in enumerate(matrix_row) if val == 1]
    if len(selected_features) == 0:
        return objective_1, 0
    X_selected = X.iloc[:, selected_features]

    # Objective 2: Maximize classification accuracy using KNN
    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)
    clf = KNeighborsClassifier()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    objective_2 = accuracy_score(y_test, y_pred)

    return objective_1, objective_2, selected_features

for iteration in range(15):
    # Use your provided genetic algorithm code here (from matrix initialization to mutation)
    # ...

    # Find the row with the lowest number of ones after mutation
    fitnesses = np.sum(transformed_matrix, axis=1)
    lowest_ones_index = np.argmin(fitnesses)

    # Calculate objectives for the best solution of this iteration
    obj1, obj2, selected_cols = calculate_fitness(transformed_matrix[lowest_ones_index], x_colon, y_colon)
    objectives.append((obj1, obj2, selected_cols))

# Apply Pareto dominance
dominated = []
for i in range(15):
    for j in range(15):
        if i != j and objectives[i][0] >= objectives[j][0] and objectives[i][1] <= objectives[j][1]:
            dominated.append(i)
            break

non_dominated_solutions = [objectives[i] for i in range(15) if i not in dominated]

print("Non-dominated solutions:\n", non_dominated_solutions)

Non-dominated solutions:
 []


In [30]:
x_colon = df.drop(columns=['Biopsy','Unnamed: 0'])
# x_colon = df.drop(columns=['Unnamed: 0'])
x_colon

Age  Number of sexual partners  First sexual intercourse  \
0     18                        4.0                   15.0000   
1     15                        1.0                   14.0000   
2     34                        1.0                   16.9953   
3     52                        5.0                   16.0000   
4     46                        3.0                   21.0000   
..   ...                        ...                       ...   
853   34                        3.0                   18.0000   
854   32                        2.0                   19.0000   
855   25                        2.0                   17.0000   
856   33                        2.0                   24.0000   
857   29                        2.0                   20.0000   

     Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
0                   1.0     0.0             0.0                  0.0   
1                   1.0     0.0             0.0                  0.0   
2                   1.0     0.0             0.0                  0.0   
3                   4.0     1.0            37.0                 37.0   
4                   4.0     0.0             0.0                  0.0   
..                  ...     ...             ...                  ...   
853                 0.0     0.0             0.0                  0.0   
854                 1.0     0.0             0.0                  0.0   
855                 0.0     0.0             0.0                  0.0   
856                 2.0     0.0             0.0                  0.0   
857                 1.0     0.0             0.0                  0.0   

     Hormonal Contraceptives  Hormonal Contraceptives (years)  IUD  ...  \
0                        0.0                              0.0  0.0  ...   
1                        0.0                              0.0  0.0  ...   
2                        0.0                              0.0  0.0  ...   
3                        1.0                              1.0  0.0  ...   
4                        1.0                              1.0  0.0  ...   
..                       ...                              ...  ...  ...   
853                      0.0                              0.0  0.0  ...   
854                      1.0                              1.0  0.0  ...   
855                      1.0                              1.0  0.0  ...   
856                      1.0                              1.0  0.0  ...   
857                      1.0                              1.0  0.0  ...   

     STDs: Number of diagnosis  STDs: Time since first diagnosis  \
0                            0                          6.140845   
1                            0                          6.140845   
2                            0                          6.140845   
3                            0                          6.140845   
4                            0                          6.140845   
..                         ...                               ...   
853                          0                          6.140845   
854                          0                          6.140845   
855                          0                          6.140845   
856                          0                          6.140845   
857                          0                          6.140845   

     STDs: Time since last diagnosis  Dx:Cancer  Dx:CIN  Dx:HPV  Dx  \
0                           5.816901          0       0       0   0   
1                           5.816901          0       0       0   0   
2                           5.816901          0       0       0   0   
3                           5.816901          1       0       1   0   
4                           5.816901          0       0       0   0   
..                               ...        ...     ...     ...  ..   
853                         5.816901          0       0       0   0   
854                         5.816901          0       0       0   0   
85

In [31]:
y_colon = df['Biopsy']
y_colon

0      0
1      0
2      0
3      0
4      0
      ..
853    0
854    0
855    0
856    0
857    0
Name: Biopsy, Length: 858, dtype: int64

In [22]:
df['Biopsy'].nunique()

2

In [23]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

np.random.seed(42)

# Create a placeholder for colon cancer dataset (replace it with your data)
  # Replace with your labels

def calculate_fitness(matrix_row, X, y):
    # Objective 1: Minimize the number of selected features
    objective_1 = sum(matrix_row)

    # Filter the columns in the dataset based on the selected features
    selected_features = [i for i, val in enumerate(matrix_row) if val == 1]
    if len(selected_features) == 0:
        return objective_1, 0
    X_selected = X.iloc[:, selected_features]

    # Objective 2: Maximize classification accuracy using KNN
    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)
    clf = KNeighborsClassifier()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    objective_2 = accuracy_score(y_test, y_pred)

    return objective_1, objective_2

# Initialize matrix
matrix = np.random.randint(0, 2, (50, 35))
print("Initial matrix:\n", matrix)

# Compute fitnesses
fitnesses = np.sum(matrix, axis=1)
print("Number of ones in each row:", fitnesses)

# Selection
S = sum(fitnesses)
selected_indices = []
for _ in range(10):
    r = np.random.uniform(0, S)
    P = 0
    for idx, f in enumerate(fitnesses):
        P += f
        if P > r:
            selected_indices.append(idx)
            break

# Crossover
transformed_matrix = matrix[selected_indices]
for i in range(0, 10, 2):
    crossover_point = np.random.randint(1, 34)
    temp = np.copy(transformed_matrix[i, :crossover_point])
    transformed_matrix[i, :crossover_point] = transformed_matrix[i+1, :crossover_point]
    transformed_matrix[i+1, :crossover_point] = temp

# Mutation
mutation_rate = 0.05
for i in range(10):
    for j in range(35):
        if np.random.rand() < mutation_rate:
            transformed_matrix[i, j] = 1 - transformed_matrix[i, j]

# Select the best individual and calculate the two objectives
fitnesses_after_mutation = np.sum(transformed_matrix, axis=1)
best_individual_index = np.argmin(fitnesses_after_mutation)
obj1, obj2 = calculate_fitness(transformed_matrix[best_individual_index], x_colon, y_colon)

print("\nObjective 1 (Min number of features):", obj1)
print("Objective 2 (KNN Accuracy):", obj2)


Initial matrix:
 [[0 1 0 ... 1 1 1]
 [0 1 0 ... 0 1 1]
 [1 1 0 ... 1 1 1]
 ...
 [0 0 1 ... 0 1 1]
 [1 1 0 ... 0 0 1]
 [1 1 0 ... 0 0 0]]
Number of ones in each row: [19 16 25 17 16 12 18 16 18 18 19 20 21 17 18 19 20 19 16 22 19 17 14 15
 15 16 16 16 21 14 11 18 20 18 15 19 14 17 21 19 16 18 14 16 18 20 13 15
 15 19]

Objective 1 (Min number of features): 13
Objective 2 (KNN Accuracy): 0.9302325581395349


**Multi-Objective Feature Selection**

In [24]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

# np.random.seed(42)

def calculate_fitness(matrix_row, X, y):
    objective_1 = sum(matrix_row)

    selected_features = [i for i, val in enumerate(matrix_row) if val == 1]
    if len(selected_features) == 0:
        return objective_1, 0, []

    X_selected = X.iloc[:, selected_features]

    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)
    clf = KNeighborsClassifier()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    objective_2 = accuracy_score(y_test, y_pred)

    return objective_1, objective_2, X_selected.columns.tolist()

results = []

for iteration in range(15):
    # Initialization
    matrix = np.random.randint(0, 2, (50, 35))
    fitnesses = np.sum(matrix, axis=1)

    # Selection
    S = sum(fitnesses)
    selected_indices = []
    for _ in range(50):
        r = np.random.uniform(0, S)
        P = 0
        for idx, f in enumerate(fitnesses):
            P += f
            if P > r:
                selected_indices.append(idx)
                break

    # Crossover
    transformed_matrix = matrix[selected_indices]
    for i in range(0, 50, 2):
        crossover_point = np.random.randint(1, 34)
        temp = np.copy(transformed_matrix[i, :crossover_point])
        transformed_matrix[i, :crossover_point] = transformed_matrix[i+1, :crossover_point]
        transformed_matrix[i+1, :crossover_point] = temp

    # Mutation
    mutation_rate = 0.05
    for i in range(50):
        for j in range(35):
            if np.random.rand() < mutation_rate:
                transformed_matrix[i, j] = 1 - transformed_matrix[i, j]

    # Calculate Fitness and Objectives for best individual
    fitnesses_after_mutation = np.sum(transformed_matrix, axis=1)
    best_individual_index = np.argmin(fitnesses_after_mutation)
    obj1, obj2, selected_columns = calculate_fitness(transformed_matrix[best_individual_index], x_colon, y_colon)

    # Store results
    results.append([obj1, ", ".join(selected_columns), obj2])
    print(f"Iteration {iteration+1}:")
    print("Objective 1 (Min number of features):", obj1)
    print("Selected features:", ", ".join(selected_columns))
    print("Objective 2 (KNN Accuracy):", obj2)
    print("="*50)

# Convert results to DataFrame and save to CSV
df_1 = pd.DataFrame(results, columns=['Objective 1', 'Selected Features', 'Objective 2'])
df.to_csv("results.csv", index=False)

Iteration 1:
Objective 1 (Min number of features): 12
Selected features: Age, Number of sexual partners, Smokes (packs/year), Hormonal Contraceptives (years), STDs:cervical condylomatosis, STDs:vaginal condylomatosis, STDs:molluscum contagiosum, STDs:HIV, STDs:Hepatitis B, STDs:HPV, STDs: Time since last diagnosis, Citology
Objective 2 (KNN Accuracy): 0.9418604651162791
Iteration 2:
Objective 1 (Min number of features): 9
Selected features: First sexual intercourse, IUD, STDs, STDs (number), STDs:vaginal condylomatosis, STDs:syphilis, STDs:AIDS, STDs: Number of diagnosis, Dx:Cancer
Objective 2 (KNN Accuracy): 0.936046511627907
Iteration 3:
Objective 1 (Min number of features): 11
Selected features: Number of sexual partners, First sexual intercourse, Num of pregnancies, Smokes (packs/year), Hormonal Contraceptives (years), STDs:syphilis, STDs:molluscum contagiosum, STDs: Time since first diagnosis, Dx:Cancer, Dx:CIN, Citology
Objective 2 (KNN Accuracy): 0.936046511627907
Iteration 4:
O

In [25]:
df_1

Objective 1                                  Selected Features  \
0            12  Age, Number of sexual partners, Smokes (packs/...   
1             9  First sexual intercourse, IUD, STDs, STDs (num...   
2            11  Number of sexual partners, First sexual interc...   
3            12  Age, Number of sexual partners, Num of pregnan...   
4             9  Smokes (packs/year), IUD, IUD (years), STDs, S...   
5            12  Age, Smokes (packs/year), Hormonal Contracepti...   
6            12  Age, Number of sexual partners, Smokes (packs/...   
7            14  First sexual intercourse, Num of pregnancies, ...   
8            10  Age, First sexual intercourse, Smokes (years),...   
9            11  First sexual intercourse, IUD, STDs, STDs (num...   
10           11  Age, Smokes (packs/year), Hormonal Contracepti...   
11           12  Age, Number of sexual partners, Num of pregnan...   
12           11  Age, Hormonal Contraceptives, Hormonal Contrac...   
13           13  First sexual intercourse, Smokes (years), Smok...   
14           11  Smokes (years), Smokes (packs/year), Hormonal ...   

    Objective 2  
0      0.941860  
1      0.936047  
2      0.936047  
3      0.924419  
4      0.936047  
5      0.936047  
6      0.930233  
7      0.941860  
8      0.936047  
9      0.959302  
10     0.936047  
11     0.924419  
12     0.930233  
13     0.924419  
14     0.959302

In [26]:
def is_dominated(row, other):
    return (row["Objective 1"] > other["Objective 1"] and row["Objective 2"] <= other["Objective 2"]) or (row["Objective 1"] >= other["Objective 1"] and row["Objective 2"] < other["Objective 2"])

def pareto_front(df_1):
    pareto_df = df_1.copy()
    indices = pareto_df.index.tolist() # Get a list of indices
    for i in indices:
        if i in pareto_df.index: # Check if index still exists in DataFrame
            row = pareto_df.loc[i]
            temp_df = pareto_df.drop(i) # Temporarily drop the current row
            dominated_rows = temp_df[temp_df.apply(is_dominated, args=(row,), axis=1)].index
            pareto_df = pareto_df.drop(dominated_rows) # Drop dominated rows
    return pareto_df

pareto_df = pareto_front(df_1)
print(pareto_df)

pareto_df.to_csv("pareto_results.csv", index=False)

    Objective 1                                  Selected Features  \
1             9  First sexual intercourse, IUD, STDs, STDs (num...   
4             9  Smokes (packs/year), IUD, IUD (years), STDs, S...   
9            11  First sexual intercourse, IUD, STDs, STDs (num...   
14           11  Smokes (years), Smokes (packs/year), Hormonal ...   

    Objective 2  
1      0.936047  
4      0.936047  
9      0.959302  
14     0.959302  


In [27]:
results=pd.read_csv('pareto_results.csv')
results

Objective 1                                  Selected Features  Objective 2
0            9  First sexual intercourse, IUD, STDs, STDs (num...     0.936047
1            9  Smokes (packs/year), IUD, IUD (years), STDs, S...     0.936047
2           11  First sexual intercourse, IUD, STDs, STDs (num...     0.959302
3           11  Smokes (years), Smokes (packs/year), Hormonal ...     0.959302

In [28]:
value =results.loc[1, 'Selected Features']
value

'Smokes (packs/year), IUD, IUD (years), STDs, STDs (number), STDs:vaginal condylomatosis, STDs:syphilis, STDs:Hepatitis B, Dx:CIN'