**Step 1 - Generate a 10x10 random matrix**

In [57]:
import numpy as np
np.random.seed(42)# To stop the random matrix from keep changing
matrix = np.random.randint(0, 2, (10, 10))# To generate matrix in form of 0 and 1
print("Initial matrix:\n", matrix)

Initial matrix:
 [[0 1 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 0 1 0 0 0]
 [0 0 1 1 1 1 1 0 1 1]
 [0 1 0 1 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 1 1]
 [1 1 0 1 0 1 1 1 0 1]
 [0 1 0 1 0 0 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 0]]


**Step 2 - Print row with lowest fitness value and Corresponding fitness function**

In [58]:
fitnesses  = np.sum(matrix, axis=1)# Count ones for each row
print("Number of ones in each row:", fitnesses )
lowest_ones_index = np.argmin(fitnesses )# Identify the row with the lowest number of ones
lowest_ones_row = matrix[lowest_ones_index].tolist()
print("Row with the lowest number of ones:", lowest_ones_row)
print("Fitness function:", fitnesses [lowest_ones_index])

Number of ones in each row: [3 4 9 4 7 4 4 7 5 9]
Row with the lowest number of ones: [0, 1, 0, 0, 0, 1, 0, 0, 0, 1]
Fitness function: 3


**Step 3 - Apply the roulette wheel Selection Algorithm**

Algorithm:-

1.   Calculate S = the sum of a finesses.
2.   Generate a random number between 0 and S.
3.   Starting from the top of the population, keep adding the finesses to the
     partial sum P, till P<S. ( Calculate cumulative sum)
4.   The individual for which P exceeds S is the chosen individual.

Example:-
1. 11010 (Fitness = 3)

  01100 (Fitness = 2)

  11110 (Fitness = 4)

  10101 (Fitness = 3)

  10000 (Fitness = 1)

  Calculate S = the sum of the fitnesses. (S=3+2+4+3+1=13)
2.Generate a random number between 0 and S. (Let's say our randomly generated number, r, is 7.4.)
3.Starting from the top of the population, keep adding the fitnesses to the partial sum P, till P<r.
Start with the first individual:

  P=3 (after adding fitness of 11010)

  Move to the second individual:

  P=5 (after adding fitness of 01100)

  Move to the third individual:

  P=9 (after adding fitness of 11110)

  Now, P has exceeded our random number, r.
4.The individual for which P exceeds r is the chosen individual.
Based on our running total, the third individual (11110 with fitness 4) makes the partial sum exceed our random number, so it's the selected individual.
 (For our random number 7.4, the selected individual from the given dataset would be 11110.)
5.Now repeat the same process for 10 times to get a 10 x 10 updated matrix


In [59]:
S = sum(fitnesses)                                                        # Calculate sum of fitnesses from each row
selected_indices = []                                                     # Initialize empty list to keep the rows selected in Roulette wheel Selection method
for _ in range(10):                                                       # Repeat 10 times to fill our new matrix
    r = np.random.uniform(0, S)                                           # This line generates a random float number between 0 and S (our total fitness)
    P = 0                                                                 # We initialize a variable P to 0.I(To keep track of the cumulative sum of fitnesses as iterating over rows.)
    for idx, f in enumerate(fitnesses):                                   # Iterate over our rows using a for-loop, getting the index (idx) and fitness value (f) of each individual.
        P += f                                                            # For every individual, we add its fitness to P.
        if P > r:                                                         # If P has exceeded our random number r. If it has, it means we have found our selected individual
            selected_indices.append(idx)                                  # We then add its index to the selected_indices list
            break

transformed_matrix = matrix[selected_indices]
print("\nTransformed matrix using Roulette Wheel Selection:")
print(transformed_matrix)



Transformed matrix using Roulette Wheel Selection:
[[1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 0 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1]
 [0 1 0 0 0 1 0 0 0 1]
 [0 0 1 1 1 0 1 0 0 0]]


**Step 4 - Applying Crossover betweeen two consecutive rows**

Algorithm:-
1. Select the crossover point
2. Flip the values after C.P. to other sides

Example:-

Given the two genes 10110 and 11011 and a crossover point of 3

Gene 1: 101 | 10

Gene 2: 110 | 11

After crossover:

New Gene 1: 101 | 11 -> 10111

New Gene 2: 110 | 10 -> 11010

Code:-

Row i:     10110

Row i+1:   11011

After crossover point at 3

New Row i:     11010

New Row i+1:   10111




In [60]:
for i in range(0, 10, 2):                                                              # Iterate over every second row of the transformed_matrix (i.e., rows with indices 0, 2, 4, 6, and 8).
                                                                                       # Each pair of consecutive rows (like rows 0 & 1, rows 2 & 3, etc.) will be involved in the crossover
    crossover_point = np.random.randint(1, 9)                                          # A random C.P. between indices 1 (inclusive) and 9 (exclusive) is generated.
    temp = np.copy(transformed_matrix[i, :crossover_point])                            # makes a copy of the portion of the row i up to the C.P. and stores in the temp variable.
    transformed_matrix[i, :crossover_point] = transformed_matrix[i+1, :crossover_point]# portion of row i up to the C.P. is replaced with the corresponding portion of the next row (i+1).
    transformed_matrix[i+1, :crossover_point] = temp                                   #The portion of row i+1 up to the C.P. is replaced with the originally copied portion of row i (stored in temp).

print("\nMatrix after Crossover:")
print(transformed_matrix)


Matrix after Crossover:
[[0 1 0 1 0 0 1 0 1 0]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 0 0 0 1 1 0 1 1]
 [0 0 1 1 1 1 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 0]
 [0 0 0 0 1 0 1 1 1 1]
 [0 0 1 1 1 1 0 0 0 1]
 [0 1 0 0 0 0 1 0 0 0]]


**Step 5 - Mutation of elements**]

Algorithm:-
1. Initialize mutation rate
2. we're visiting each element of the matrix and generating a random number between 0 and 1. If this number is less than M.R. the element (or gene) undergoes mutation.

Example:-
1. Initialize mutation rate= 0.05
2. For element (1,1) = 0:

  Random number generated = 0.07

  Since 0.07 is not less than 0.05, no mutation happens.

  For element (1,2) = 1:

  Random number generated = 0.03

  Since 0.03 is less than 0.05, we mutate. The value changes from 1 to 0.

  ... And so on for each element of the matrix.


In [61]:
mutation_rate = 0.05                                                # 5% mutation rate( Probblity of gene to go under mutation )
for i in range(10):                                                 # Nested loops to iterate over each element of the transformed_matrix, which is assumed to be of size 10x10
    for j in range(10):                                             # For each gene in the matrix, a random number between 0 and 1 is generated
        if np.random.rand() < mutation_rate:                        # if this random number is less than the M.R., the condition becomes true, then element should undergo mutation.
            transformed_matrix[i, j] = 1 - transformed_matrix[i, j] # If the value of the gene is 0, it becomes 1 - 0 = 1. and if  1, then becomes 1 - 1 = 0.

print("\nMatrix after Mutation:")
print(transformed_matrix)


Matrix after Mutation:
[[0 1 0 1 0 0 0 0 1 0]
 [0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 0 1 1 1 1 1 0]
 [1 1 0 0 0 1 1 0 1 1]
 [0 0 1 1 1 1 1 1 1 0]
 [1 0 1 0 1 1 1 1 1 0]
 [0 0 0 0 1 0 1 1 1 1]
 [0 0 1 1 1 1 1 0 0 1]
 [0 1 0 0 0 0 1 0 0 0]]
